-- Part 2: 创建索引 + 插入默认数据
CREATE INDEX IF NOT EXISTS messages_session_id_idx ON messages(session_id);
CREATE INDEX IF NOT EXISTS messages_created_at_idx ON messages(created_at);
CREATE INDEX IF NOT EXISTS staff_users_username_idx ON staff_users(username);
CREATE INDEX IF NOT EXISTS staff_users_business_id_idx ON staff_users(business_id);
CREATE INDEX IF NOT EXISTS staff_users_business_slug_idx ON staff_users(business_slug);
CREATE INDEX IF NOT EXISTS robot_knowledge_keyword_idx ON robot_knowledge(keyword);
CREATE INDEX IF NOT EXISTS evaluations_session_id_idx ON evaluations(session_id);
CREATE INDEX IF NOT EXISTS sessions_visiter_id_idx ON sessions(visiter_id);
CREATE INDEX IF NOT EXISTS sessions_business_id_idx ON sessions(business_id);
CREATE INDEX IF NOT EXISTS sentences_staff_id_idx ON sentences(staff_id);
CREATE INDEX IF NOT EXISTS offline_messages_created_at_idx ON offline_messages(created_at);
CREATE INDEX IF NOT EXISTS queue_visiter_id_idx ON queue(visiter_id);
CREATE INDEX IF NOT EXISTS queue_business_id_idx ON queue(business_id);
CREATE INDEX IF NOT EXISTS visitors_business_id_idx ON visitors(business_id);
CREATE INDEX IF NOT EXISTS visitors_visitor_id_idx ON visitors(visitor_id);
CREATE INDEX IF NOT EXISTS admin_users_username_idx ON admin_users(username);
CREATE INDEX IF NOT EXISTS roles_name_idx ON roles(name);
CREATE INDEX IF NOT EXISTS transfer_requests_session_id_idx ON transfer_requests(session_id);
CREATE INDEX IF NOT EXISTS transfer_requests_to_staff_id_idx ON transfer_requests(to_staff_id);
CREATE INDEX IF NOT EXISTS transfer_requests_from_staff_id_idx ON transfer_requests(from_staff_id);
CREATE INDEX IF NOT EXISTS visitor_custom_fields_business_id_idx ON visitor_custom_fields(business_id);
CREATE INDEX IF NOT EXISTS visitor_custom_fields_field_key_idx ON visitor_custom_fields(business_id, field_key);
CREATE INDEX IF NOT EXISTS idx_business_domains_domain ON business_domains(domain);
CREATE INDEX IF NOT EXISTS idx_business_domains_business_id ON business_domains(business_id);
CREATE INDEX IF NOT EXISTS idx_business_domains_type_status ON business_domains(domain_type, status);
CREATE INDEX IF NOT EXISTS idx_business_ai_config_business_id ON business_ai_config(business_id);
CREATE INDEX IF NOT EXISTS idx_domain_logs_business_id ON domain_operation_logs(business_id);
CREATE INDEX IF NOT EXISTS idx_domain_logs_created_at ON domain_operation_logs(created_at);
INSERT OR REPLACE INTO admin_users (username, password_hash, email, name, status) VALUES ('admin', '8d969eef6ecad3c29a3a629280e686cf0c3f5d5a86aff3ca12020c923adc6c92', 'admin@example.com', '系统管理员', 'active');
INSERT OR REPLACE INTO staff_users (username, password_hash, email, name, role, status, enable_auto_trans, default_lang, business_id, business_slug, business_name) VALUES ('admin', '8d969eef6ecad3c29a3a629280e686cf0c3f5d5a86aff3ca12020c923adc6c92', 'admin@example.com', '系统管理员', 'admin', 'active', 1, 'zh-CN', 0, 'default', '默认商家');
INSERT OR REPLACE INTO roles (name, description, permissions, is_system, status) VALUES ('超级管理员', '系统默认超级管理员', '["admin_view","admin_edit","staff_view","staff_edit","role_view","role_edit","settings"]', 1, 'active');
INSERT OR REPLACE INTO admin_config (key, value, description) VALUES ('siteName', 'CF智能多语言在线客服系统', '网站名称');
INSERT OR REPLACE INTO admin_config (key, value, description) VALUES ('defaultLanguage', 'zh-CN', '默认语言');
INSERT OR REPLACE INTO admin_config (key, value, description) VALUES ('enableAuth', 'true', '启用认证');
